steps:
  - id: "Installing dependencies"
    name: "gcr.io/cloud-builders/go"
    args: ['install', 'hello']
    env:
      - GOPATH=.

  - id: "Running tests"
    name: "gcr.io/cloud-builders/go"
    args: ['test', 'hello']
    env:
      - GOPATH=.

  - id: "Building image from Dockerfile"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/go-cd:$SHORT_SHA','-f','Dockerfile.prod','.']

  - id: "Pushing image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/go-cd:$SHORT_SHA']

  - id: 'Adjusting deployment file - k8s'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - | 
        sed 's#img-app-deployment#gcr.io/$PROJECT_ID/go-cd:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
        cat k8s/deployment-new.yaml;

  - id: 'Deploy k8s'
    name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment-new.yaml'
    env: 
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-fullcycle'